language: java
services:
  - docker
env:
  global: 
    - DOCKER_IMAGE=travis-ci-demo
cache:
  directories:
    - $HOME/.m2
script:
  - mvn test -B
  - docker build -t $DOCKER_IMAGE .
deploy: 
  provider: script
  script: bash .travis/docker-push.sh
  on:
    tags: true
